sp_backend:
    resource: "@SPBackendBundle/Resources/config/routing.yml"
    prefix:   /backend

sp_plateform:
    resource: "@SPPlateformBundle/Resources/config/routing.yml"
    prefix:   /plateform

sp_core:
    resource: "@SPCoreBundle/Resources/config/routing.yml"
    prefix:   /