<?php

namespace SP\BackendBundle\Repository;

/**
 * DonneeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DonneeRepository extends \Doctrine\ORM\EntityRepository
{
}
